INTYGFV-16460: Added aggregation for send
sklintyg/webcert pull request #1010
Opened 2024-03-21 10:49 UTC by mhornfeldt

2024-03-21 12:09 UTC, ChrilleSigerhed approved these changes
Nice and clean, well done!

2024-03-22 05:38 UTC, mww-sopra-steria requested changes
See the mapping of Previous and Signed List. When Sent, it should set the status to "SENT".

2024-03-22 05:38 UTC, mww-sopra-steria commented on web/src/main/java/se/inera/intyg/webcert/web/csintegration/certificate/SendCertificateFromCertificateService.java
> +        return certificate.getMetadata().getId();
The Webcert-implementation returns OK if successfully sent and returns FAILED is not. Double check the implementation by comparing to the Webcert-facade implementation.

2024-03-25 09:56 UTC, mww-sopra-steria requested changes
Nice! Works well not in Webcert, but there is another tweak that is necessary.

In CertificateListItemConverterImpl on row 80-82 there needs to be special handling for converting ListIntygEntry to correct status based on the ListType.CERTIFICATES. It should consider the status (matches "SENT") instead of being hardcoded to false (was not introduced in this pr).

2024-03-26 09:22 UTC, mww-sopra-steria approved these changes
Nice! Approved!

2024-03-26 12:34 UTC, merged