INTYGFV-14288: If patient is protected then body should be sent for print link
sklintyg/webcert pull request #609
Opened 2021-12-13 13:25 UTC by mhornfeldt

2021-12-13 14:56 UTC, RobertDanielsson approved these changes

2021-12-14 11:57 UTC, mww-sopra-steria requested changes

2021-12-14 11:57 UTC, mww-sopra-steria commented on web/src/main/java/se/inera/intyg/webcert/web/service/facade/impl/GetCertificatesAvailableFunctionsImpl.java
> +        addPrintResourceLink(certificate, resourceLinks);
Consider having a getMethod that returns a print resourcelink instead of passing in the list and adding it inside the method.

2021-12-29 12:51 UTC, mww-sopra-steria approved these changes

2021-12-29 12:52 UTC, merged