INTYGFV-14460: Added facade service for getting patient from PU
sklintyg/webcert pull request #658
Opened 2022-03-10 09:58 UTC by mhornfeldt

2022-03-10 14:55 UTC, perfli approved these changes

2022-03-10 14:55 UTC, perfli commented on web/src/main/java/se/inera/intyg/webcert/web/service/facade/patient/GetPatientFacadeService.java
> +public interface GetPatientFacadeService {
Not a biggie but I think we should avoid verbs in class names. Also, it seems redundant to have both `Facade` and `Service` in the name. Perhaps we could rename it to `PatientFacade` or `PatientService`?

2022-03-10 14:55 UTC, perfli commented on web/src/main/java/se/inera/intyg/webcert/web/service/facade/patient/GetPatientFacadeServiceImpl.java
> +    private static final Logger LOG = LoggerFactory.getLogger(PatientController.class);
Should the logger be instantiated with the current class?
```suggestion
    private static final Logger LOG = LoggerFactory.getLogger(GetPatientFacadeServiceImpl.class);
```

2022-03-10 14:55 UTC, perfli commented on web/src/main/java/se/inera/intyg/webcert/web/service/facade/patient/GetPatientFacadeServiceImpl.java
> +        return personSvar.getPerson().getFornamn() + " " + personSvar.getPerson().getMellannamn() + " " + personSvar.getPerson().getEfternamn();
The code would be easier to read/process if we introduce a variable for `personSvar.getPerson()`
```suggestion
        final var person = personSvar.getPerson();
        if (person.getMellannamn() == null || person.getMellannamn().length() == 0) {
            return person.getFornamn() + " " + person.getEfternamn();
        }
        return person.getFornamn() + " " + person.getMellannamn() + " " + person.getEfternamn();
```

2022-03-10 14:55 UTC, perfli commented on web/src/test/java/se/inera/intyg/webcert/web/service/facade/impl/GetPatientFacadeServiceImplTest.java
> +        setupPatient(false, false, false, true);
Not important enough to fix for this code, and perhaps IntelliJ gives a slightly better developer experience, but method signatures like this generally is a bad idea.

2022-03-13 13:03 UTC, mww-sopra-steria requested changes
Good that you didn't implement any logic inside the controller, but instead included it in the facade-service. 

To follow the same pattern as our other facade-controllers and services, try to move the DTO-creation to the PatientController. I noticed that PersonSvar has a status that you need to deal with. Feel free to ping me if you like to discuss options.

2022-03-14 12:29 UTC, mhornfeldt commented
> Good that you didn't implement any logic inside the controller, but instead included it in the facade-service.
> 
> To follow the same pattern as our other facade-controllers and services, try to move the DTO-creation to the PatientController. I noticed that PersonSvar has a status that you need to deal with. Feel free to ping me if you like to discuss options.

Right now I need both the status and the patient from the service so that's why I create the DTO there. Do you mean I should only return the patient? In that case how should I handle errors in the frontend which signals that a patient was not found by PU? There are two error messages which I've implemented, one for NOT_FOUND and one when the API-call failed.

2022-03-15 15:27 UTC, mww-sopra-steria approved these changes

2022-03-15 15:28 UTC, merged