INTYGFV-14459: Added resource links for user
sklintyg/webcert pull request #659
Opened 2022-03-14 14:05 UTC by mhornfeldt

2022-03-15 14:07 UTC, mww-sopra-steria requested changes
Two small things to look into, but other than that it looks good!

2022-03-15 14:13 UTC, mhornfeldt commented on web/src/main/java/se/inera/intyg/webcert/web/web/controller/facade/dto/ResourceLinkTypeDTO.java
> +    CREATE_CERTIFICATE,
Searching for a patient and creating a certificate is in the same tab in the application. If you haven't searched for a patient you won't see the create certificate section, so I was thinking that the resource link would handle both functions. I can change the name.

2022-03-15 14:16 UTC, mhornfeldt commented on web/src/main/java/se/inera/intyg/webcert/web/service/facade/impl/GetUserResourceLinksImpl.java
> +public class GetUserResourceLinksImpl implements GetUserResourceLinks {
When you say have the user as an argument do you mean of class User or WebCertUser? If we don't use the WebCertUser coming from the webcertUserService we don't get access to the origin of the user.

2022-03-15 15:31 UTC, mww-sopra-steria commented on web/src/main/java/se/inera/intyg/webcert/web/web/controller/facade/dto/ResourceLinkTypeDTO.java
> +    CREATE_CERTIFICATE,
Sounds good that it handles both. It makes sense. But maybe think about a name-pattern that also makes sense for the other "tabs" like 'Signerade intyg' etc.

2022-03-18 07:29 UTC, mww-sopra-steria approved these changes

2022-03-31 04:43 UTC, mww-sopra-steria requested changes
It looks good! I like that you have created a ResourceLinkFacadeTestHelper! Could you see if there are more test classes that could be refactored to use the helper? For example GetQuestionsAvailableFunctions.

The changes in UserServiceImpl looks good, but could you limit to SITHS, FAKE and BANK_ID? We don't support any other login methods in the React-client and it is probably better not to expose anything else to the client.

2022-03-31 06:59 UTC, mikeyOne approved these changes

2022-03-31 12:47 UTC, merged