INTYGFV-14462: Implemented list for previous certificates of patient
sklintyg/webcert pull request #681
Opened 2022-04-28 08:35 UTC by mhornfeldt

2022-05-03 08:09 UTC, mhornfeldt commented
@mww-sopra-steria Do you think I should moved the button types (OPEN_BUTTON, SEARCH_BUTTON, RENEW_BUTTON) to its own type instead of having it as a CertificateListItemValueType? For open and renew it makes sense to have them here because they are values of the table. The search button instead is not. I use the ID's to save/access the button tooltips in a map.

2022-05-03 12:13 UTC, mww-sopra-steria requested changes
Well done! Quite easy to read most of the code!

Have just a few comments to look at. Minor things.

Relating your question, I don't have an opinion on the matter. Maybe because I can't see the implications of the different alternatives. Follow your judgement and consider maintainability.

2022-05-03 12:13 UTC, mww-sopra-steria commented on web/src/main/java/se/inera/intyg/webcert/web/service/facade/list/ResourceLinkListHelperImpl.java
> +        } else if (validateRenew(link, certificateType, relations, getCertificateStatus(status))) {
Little tricky code to read... but you could remove the else and just do an if. Could make it little more readable.

2022-05-03 12:13 UTC, mww-sopra-steria commented on web/src/main/java/se/inera/intyg/webcert/web/service/facade/list/config/GetStaffInfoFacadeService.java
> +    List<String> getUnits();
Could this be be changed to a little more readable name. You don't understand what it returns until you read the actual implementation.

2022-05-03 12:13 UTC, mww-sopra-steria commented on web/src/main/java/se/inera/intyg/webcert/web/service/facade/list/config/GetStaffInfoFacadeServiceImpl.java
> +        WebCertUser webCertUser = webCertUserService.getUser();
Use final var instead for consistency.

2022-05-16 06:41 UTC, mww-sopra-steria approved these changes

2022-05-17 11:25 UTC, merged