INTYGFV-15649: Changed default login to siths-wc2 in IdpSelectionFilter.
sklintyg/webcert pull request #898
Opened 2023-07-20 06:20 UTC by ChrilleSigerhed

2023-07-31 06:43 UTC, mhornfeldt approved these changes

2023-07-31 07:54 UTC, mww-sopra-steria requested changes
Check if /maillink url also need to be handled with wc2 sp metadata.

2023-08-07 07:16 UTC, ChrilleSigerhed commented
> 

After looking into this I found that the maillink uses the following urlBaseTemplate url:
```/webcert/web/user/basic-certificate```

This implies that the changes provided also will affect users that launches webcert from a mail link.

2023-08-08 05:40 UTC, mww-sopra-steria approved these changes

2023-08-08 05:42 UTC, mww-sopra-steria commented
@ChrilleSigerhed Consider adding unit test for the added behaviour and changed metadata.

2023-08-08 07:39 UTC, merged